class LocalizationService {
  static const Map<String, Map<String, String>> _t = {
    'fr': {
      'irreversible': 'Cette action est irréversible.',
      'app_name': 'MENANA ORGANIC FOOD',
      'abs_232': 'Absorbance 232 nm',
'abs_270': 'Absorbance 270 nm',
'abs_274': 'Absorbance 274 nm',
'abs_266': 'Absorbance 266 nm',
      'laboratory': 'Laboratoire de Contrôle Qualité',
      'login': 'Connexion',
      'register': 'Créer un compte',
      'username': 'Nom d\'utilisateur',
      'password': 'Mot de passe',
      'confirm_password': 'Confirmer le mot de passe',
      'create_account': 'Créer un compte',
      'no_account': 'Pas encore de compte ?',
      'have_account': 'Vous avez déjà un compte ?',
      'empty_fields': 'Veuillez remplir tous les champs',
      'passwords_not_match': 'Les mots de passe ne correspondent pas',
      'password_short': 'Minimum 6 caractères',
      'invalid_credentials': 'Identifiants invalides',
      'username_exists': 'Ce nom d\'utilisateur existe déjà',
      'username_not_found': 'Nom d\'utilisateur introuvable',
      'password_incorrect': 'Mot de passe incorrect',
      'registration_success': 'Compte créé ! Veuillez vous connecter.',
      'demo_creds': 'Identifiants de démonstration :',
      'admin_user': 'Administrateur',
      'logout': 'Déconnexion',
      'hello': 'Bonjour',
      'quick_actions': 'Actions rapides',
      'new_analysis': 'Nouvelle Analyse',
      'new_analysis_sub': 'Saisir les données de l\'huile',
      'history': 'Historique',
      'history_sub': 'Consulter les analyses passées',
      'admin': 'Admin',
      'admin_panel': 'Panneau Administrateur',
      'dashboard': 'Tableau de bord',
      'all_analyses': 'Toutes les analyses',
      'quick_stats': 'Statistiques rapides',
      'total_analyses': 'Total',
      'compliant': 'Conformes',
      'non_compliant': 'Non conformes',
      'conformity_rate': 'Taux %',
      'conformity_distribution': 'Répartition des résultats',
      'recent_analyses': 'Analyses récentes',
      'see_all': 'Voir tout →',
      'last_analysis': 'Dernière analyse',
      'search_analysis': 'Rechercher par code, client, date…',
      'no_data': 'Aucune analyse enregistrée',
      'confirm_delete': 'Confirmer la suppression',
      'delete_msg': 'Supprimer l\'analyse',
      'distribution_results': 'Distribution des résultats',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'deleted': 'Analyse supprimée avec succès',
      'new_analysis_form': 'Nouvelle Analyse',
      'modifier': 'Modifier l\'analyse',
      'sample_code': 'Code échantillon *',
      'client_name': 'Nom du client *',
      'client_code': 'Code client *',
      'oil_quantity': 'Quantité d\'huile (L)',
      'reception_date': 'Date réception *',
      'analysis_date': 'Date analyse *',
      'free_acidity': 'Acidité libre (%) *',
      'standard': 'Norme',
      'uv_analysis_k232': 'Analyse UV – K232',
      'uv_analysis_k270': 'Analyse UV – K270 / K274 / K266',
      'mass': 'Masse (g)',
      'voir': 'Voir',
      'calculated': 'calculé',
      'fill_fields': 'Complétez les champs pour voir le résultat',
      'save': 'Enregistrer',
      'update': 'Mettre à jour',
      'saved': 'Analyse enregistrée avec succès',
      'error': 'Erreur',
      'version': 'Version',
      'offline_mode': 'Mode hors ligne',
      'quick_actions_label': 'Actions',
      "analysis_saved": "Analyse enregistrée avec succès",
      "analysis_updated": "Analyse mise à jour avec succès",
      'analysis_found': 'Analyse trouvée',
      'no_analysis_found': 'Aucune analyse trouvée',
      'client': 'Client',
      'date': 'Date',
      'code': 'Code',
      
      'delta_k': 'Delta K',
      'actions': 'Actions',
    },
    'ar': {
      'distribution_results': 'توزيع النتائج',
    
      'voir': 'عرض',
'modifier': 'تعديل التحليل',
    'analysis_saved': 'تم حفظ التحليل بنجاح',
    'analysis_updated': 'تم تحديث التحليل بنجاح',
      'app_name': 'MENANA الغذاء العضوي',
      'laboratory': 'مختبر مراقبة الجودة',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'create_account': 'إنشاء حساب',
      'no_account': 'ليس لديك حساب؟',
      'have_account': 'لديك حساب بالفعل؟',
      'empty_fields': 'يرجى ملء جميع الحقول',
      'passwords_not_match': 'كلمات المرور غير متطابقة',
      'password_short': 'الحد الأدنى 6 أحرف',
      'invalid_credentials': 'بيانات غير صحيحة',
      'username_exists': 'اسم المستخدم موجود',
      'username_not_found': 'اسم المستخدم غير موجود',
      'password_incorrect': 'كلمة المرور غير صحيحة',
      'registration_success': 'تم إنشاء الحساب! يرجى تسجيل الدخول.',
      'demo_creds': 'بيانات تجريبية:',
      'admin_user': 'المسؤول',
      'logout': 'تسجيل الخروج',
      'hello': 'مرحباً',
      'quick_actions': 'إجراءات سريعة',
      'new_analysis': 'تحليل جديد',
      'new_analysis_sub': 'إدخال بيانات الزيت',
      'history': 'السجل',
      'history_sub': 'عرض التحليلات السابقة',
      'admin': 'إدارة',
      'admin_panel': 'لوحة الإدارة',
      'dashboard': 'لوحة التحكم',
      'all_analyses': 'جميع التحليلات',
      'quick_stats': 'إحصائيات سريعة',
      'total_analyses': 'الإجمالي',
      'compliant': 'متوافق',
      'non_compliant': 'غير متوافق',
      'conformity_rate': 'نسبة %',
      'conformity_distribution': 'توزيع النتائج',
      'recent_analyses': 'التحليلات الأخيرة',
      'see_all': 'عرض الكل →',
      'last_analysis': 'آخر تحليل',
      'search_analysis': 'بحث...',
      'no_data': 'لا توجد تحليلات',
      'confirm_delete': 'تأكيد الحذف',
      'delete_msg': 'حذف التحليل',
      'irreversible': 'هذا الإجراء لا يمكن التراجع عنه.',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'deleted': 'تم حذف التحليل',
      'save': 'حفظ',
      'update': 'تحديث',
      'saved': 'تم حفظ التحليل',
      'error': 'خطأ',
      'version': 'الإصدار',
      'offline_mode': 'وضع عدم الاتصال',
      'standard': 'المعيار',
      'uv_analysis_k232': 'تحليل UV – K232',
      'uv_analysis_k270': 'تحليل UV – K270 / K274 / K266',
      'mass': 'الكتلة (جم)',
      'calculated': 'المحسوبة',
      'fill_fields': 'أكمل الحقول لرؤية النتيجة',
      'sample_code': 'رمز العينة *',
      'client_name': 'اسم الحريف *',
      'client_code': 'رمز الحريف *',
      'oil_quantity': 'كمية الزيت (لتر)',
      'reception_date': 'تاريخ القبول *',
      'analysis_date': 'تاريخ التحليل *',
      'free_acidity': 'الحموضة (%) *',
      'new_analysis_form': 'تحليل جديد',
      'edit_analysis': 'تعديل التحليل',
      'quick_actions_label': 'إجراءات',
      'abs_232': 'إمتصاص ضوء 232',
'abs_270': 'إمتصاص ضوء 270',
'abs_274': 'إمتصاص ضوء 274',
'abs_266': 'إمتصاص ضوء 266',
'analysis_found': 'تم العثور على التحليل',
'no_analysis_found': 'لم يتم العثور على أي تحليل',
'code': 'رمز',
'client': 'الحريف',
'date': 'تاريخ',
'delta_k': 'دلتا K',
'actions': 'إجراءات',
    },

    'en': { 'irreversible': 'This action is irreversible.',
    'distribution_results': 'Results Distribution',
      'modifier': 'Edit Analysis',
      'voir': 'View',
      'analysis_saved': 'Analysis saved successfully',
      'analysis_updated': 'Analysis updated successfully',
      'app_name': 'MENANA ORGANIC FOOD',
      'laboratory': 'Quality Control Laboratory',
      'login': 'Login',
      'register': 'Create Account',
      'username': 'Username',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'create_account': 'Create Account',
      'no_account': 'Don\'t have an account?',
      'have_account': 'Already have an account?',
      'empty_fields': 'Please fill all fields',
      'passwords_not_match': 'Passwords do not match',
      'password_short': 'Minimum 6 characters',
      'invalid_credentials': 'Invalid credentials',
      'username_exists': 'Username already taken',
      'username_not_found': 'Username not found',
      'password_incorrect': 'Incorrect password',
      'registration_success': 'Account created! Please login.',
      'demo_creds': 'Demo credentials:',
      'admin_user': 'Administrator',
      'logout': 'Logout',
      'hello': 'Hello',
      'quick_actions': 'Quick Actions',
      'new_analysis': 'New Analysis',
      'new_analysis_sub': 'Enter oil sample data',
      'history': 'History',
      'history_sub': 'View past analyses',
      'admin': 'Admin',
      'admin_panel': 'Admin Panel',
      'dashboard': 'Dashboard',
      'all_analyses': 'All Analyses',
      'quick_stats': 'Quick Stats',
      'total_analyses': 'Total',
      'compliant': 'Compliant',
      'non_compliant': 'Non-Compliant',
      'conformity_rate': 'Rate %',
      'conformity_distribution': 'Results Distribution',
      'recent_analyses': 'Recent Analyses',
      'see_all': 'See all →',
      'last_analysis': 'Last Analysis',
      'search_analysis': 'Search by code, client, date…',
      'no_data': 'No analyses recorded',
      'confirm_delete': 'Confirm deletion',
      'delete_msg': 'Delete analysis',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'deleted': 'Analysis deleted successfully',
      'save': 'Save',
      'update': 'Update',
      'saved': 'Analysis saved successfully',
      'error': 'Error',
      'version': 'Version',
      'offline_mode': 'Offline mode',
      'standard': 'Standard',
      'uv_analysis_k232': 'UV Analysis – K232',
      'uv_analysis_k270': 'UV Analysis – K270 / K274 / K266',
      'mass': 'Mass (g)',
      'calculated': 'calculated',
      'fill_fields': 'Fill in fields to see the result',
      'sample_code': 'Sample Code *',
      'client_name': 'Client Name *',
      'client_code': 'Client Code *',
      'oil_quantity': 'Oil Quantity (L)',
      'reception_date': 'Reception Date *',
      'analysis_date': 'Analysis Date *',
      'free_acidity': 'Free Acidity (%) *',
      'new_analysis_form': 'New Analysis',
      'edit_analysis': 'Edit Analysis',
      'quick_actions_label': 'Actions',
      'abs_232': 'Absorbance 232 nm',
'abs_270': 'Absorbance 270 nm',
'abs_274': 'Absorbance 274 nm',
'abs_266': 'Absorbance 266 nm',
'analysis_found': 'Analysis found',
'no_analysis_found': 'No analysis found',
'code': 'Code',
'client': 'Client',
'date': 'Date',
'delta_k': 'Delta K',
'actions': 'Actions',
    },
  };

  static String translate(String key, String language) =>
      _t[language]?[key] ?? _t['en']?[key] ?? key;
}